config/routes.rb
PhotoContest::Application.routes.draw do
    devise_for :users

    get "contestants/new"

    match 'contestant_entries/top_ten', :to =>  "contestant_entries#top_ten" , :as => :top_ten
    match 'contestant_entries/stats', :to =>  "contestant_entries#stats" , :as => :stats

    resources :contestants         
    resources :contestant_entries  
    
    #contest terminated
    match '/enter',   :to =>   'pages#enter'      
    #contest is running    
    #match '/enter',   :to =>   'contestants#new'  
  
    match '/rules',   :to =>   'pages#rules'
    match 'home',  :to =>  'pages#home'   
    root :to => 'pages#home' 

end

app/models/contestant_entry.rb
class ContestantEntry < ActiveRecord::Base
  belongs_to :contestant
  has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  
  attr_accessible :photo, :rating , :first_name, :last_name, :address, :address2,
                  :city, :state, :zip, :phone, :photographer, :location, :contest_source,
                  :agreed_to_rules, :month_rated_for

  
  validate :limit_to_three_entries , :on => :create
  
  validates_attachment_presence :photo, :message => "You must attach a photo."                    

  # #problematic call, handling in a custom method
  #  validates_attachment_size  :photo,:less_than=>20.megabyte,:greater_than=>1.megabyte,:message => "Photo size must be between 1 and 20 Megabytes",:allow_nil => true



   def self.stats
    begin
 
      stats = Hash.new
      # Total Submissions  -- total = select count(*) from contestant_entries 
      total_entries = ContestantEntry.connection.select_one("SELECT count(*) as total_entries 
                                                               FROM contestant_entries")
 
      stats = stats.merge(total_entries)
 

      total_rated =  ContestantEntry.connection.select_one("SELECT count(*) as total_rated
                                                              FROM contestant_entries 
                                                              WHERE rating is not null")
 
      stats = stats.merge(total_rated)
      
      total_unrated = total_entries["total_entries"]- total_rated["total_rated"]
      stats["total_unrated"] = total_unrated
 
      return stats
    end    
  end 
  
  #image/pjpeg is for IE compatality
  
  validates_attachment_content_type :photo, :content_type=>['image/jpeg', 'image/png', 'image/tiff', 'image/pjpeg']   
  validate :size_acceptable, :on => :create
  validates :agreed_to_rules, :presence     => true  
  validates :first_name, :presence => true
  validates :last_name, :presence => true      
  validates :address, :presence => true
  
  validates :city, :presence => true
  validates :state, :presence => true
  validates :zip, :presence => true, :numericality => true, :length => { :is => 5 }
  validates :phone, :presence => true
  validates :photographer, :presence => true
  validates :location, :presence => true
  validates :contest_source, :presence => true
 
  private
  #make sure there are only three contesant entries for the corresponding contesant  
  def limit_to_three_entries    
    begin
      #todo  review test coverage
      #get prior entries from corresponding contesant      
      #no entries, no problem      
      if self.contestant.blank?    
        return
      else
        prior_entries = self.contestant.contestant_entries        
      #less than thee, no problem
      end
      if prior_entries.size < 3      
        return 
      else  
       errors.add(:base, "You are only allowed 3 entries.") 
      end
    end    
  end

  private
  
  def size_acceptable    
      if photo.nil? || photo.size.nil?
        return
      end
      size = photo.size
      if  size >20.megabyte
        errors.add(:photo, "Size must be smaller than 20 megabytes.")
      elsif   size < 1.megabyte
         errors.add(:photo, "Size must be greater than 1 megabyte.")
      end    
  end
  
end

app/controllers/contestant_entries_controller.rb
class ContestantEntriesController < ApplicationController
  before_filter :authenticate_user!
      
  def index
    @contestants = Contestant.paginate(:page => params[:page], :per_page => 10)
  end

  def update
   @contestants = Contestant.paginate(:page => params[:page], :per_page => 10)   
   entry = ContestantEntry.find(params[:id])   
   entry.rating = params[:entry][:rating]
   entry.month_rated_for = params[:entry][:month_rated_for]  
   if entry.save
    flash[:notice] = "Vote recorded for #{entry.contestant.email}"
    redirect_to contestant_entries_path   
   else    
    flash[:now] = "Your rating for #{entry.contestant.email} was not saved.  Please put a numeric rating"
    redirect_to contestant_entries_path
   end   
  end
  
  def show
    @entry =  ContestantEntry.find(params[:id])
  end

  def top_ten
    @ratings_by_month = get_ratings_by_month    
  end 

  def stats
    @stats = ContestantEntry.stats
  end  

  private


  def get_ratings_by_month
    #move to model
    entries = ContestantEntry.find_by_sql(
                 "SELECT 
                   rating, 
                   month_rated_for, 
                   id, 
                   contestant_id, 
                   photo_file_name, 
                   photo_content_type 
                  FROM  contestant_entries
                  WHERE rating is not null 
                  ORDER by month_rated_for,  rating"
                  )
     
     # An hash of arrays for the ratings by month 
     ratings_by_month =  Hash.new
     # aggregate entries for each month
     (1..12).each do |i| 
       # select all the entries rated for the curren month i into a new array
       one_months_ratings = entries.select{ |entry| entry.month_rated_for == i }       
       
       #put it in the bucket      
       ratings_by_month[i] =  one_months_ratings     
       
 
     end
     # and an extra slot for month not specified 
     ratings_by_month[13] = entries.select{ |entry| entry.month_rated_for.nil? }       

     return  ratings_by_month  
  end 
  

end

app/helpers/contestant_entry_helper.rb
module ContestantEntryHelper
  
   def get_entry (entries, entry_number)     
     return entries[entry_number-1] unless entries.nil?
   end
   
   def list_of_numbers(upper_bound)
     list = Hash.new
     nums = (1..upper_bound).to_a
     nums.each do |i|
       list[i.to_s] = i.to_s
     end
   end
   
end

app/views/contestant_entries/_entry.html.erb
<div class="rating_form">
<%= image_tag entry.photo.url(:thumb), :class => "entry_image" %>  
  <span class="rating_form">    
<%= form_for entry  do |f| %>    
    <%= f.error_messages %>
      <% if entry.rating %>    
        <span class="prior">Prior Rating:<strong><%=  entry.rating %></strong>
        For Month:<strong><%= get_month_if_rated (entry) %></strong></span>
      <% else %>
        <span class="prior"><strong>Unrated</strong></span>  
      <% end %>
      
      <span><%= f.label :rating, "Rating:",:class=>"rating_form_lab"%>
    <%= select( :entry, :rating, list_of_numbers(5),  ) %></span>
    <span><%= f.label :month, "Month:", :class=>"rating_form_lab" %>
          <%= select_month(0,:prefix =>"entry",  :field_name=> "month_rated_for",
                            :use_short_month => true, :prompt=>"Pick Month") %>
    </span>
    <span><%= f.submit "Submit Vote",  :class=>"rating_but" %></span>
    <span><%= link_to "Details", contestant_entry_path(entry),  :class=>"details_link"%></span>
 <% end %><!-- rating form -->    

 </span>   
</div>

app/views/contestant_entries/index.html.erb
<span class="entersubhead">Contest Gallery</span>
<table id="gallery">
  <%= will_paginate  @contestants %>
  <% @contestants.each do |contestant| %>    
    <tr class="contestant_email_grid" width="100%">
      <td colspan="3">
         Contestant Email: <%= contestant.email %>
      </td>
    </tr>
    <tr class="contestant_entry_entries">
      <td class="contestant_entry">
        <% entry = get_entry contestant.contestant_entries,  1%>
        <% if not entry.nil? %>
        <%=  render  :partial => 'entry' , :object => entry%>
      <% end %>
      </td>
      <td class="contestant_entry">
        <% entry = get_entry contestant.contestant_entries,  2%>
        <% if not entry.nil? %>
        <%=  render  :partial => 'entry' , :object => entry%>
      <% end %>
      </td>
      <td class="contestant_entry">
        <% entry = get_entry contestant.contestant_entries,  3%>
        <% if not entry.nil? %>
        <%=  render  :partial => 'entry' , :object => entry%>
      <% end %>
      </td> 
    </tr>
  <% end %><!-- end unique contestant loop-->
</table>

app/views/contestant_entries/show.html.erb
<div id="image_detail">
  <%= image_tag @entry.photo.url(:medium), :class => "@entry_image" %>
</div>
<div id="entry_entry_details">  
<% unless @entry.rating.nil?  %>  
    <p class="entry_detail" ><label class="entry_details">Rating:</label>
      <%= @entry.rating %></p>
    <p class="entry_detail" ><label class="entry_details">Month:</label>  
      <%= get_month_if_rated(@entry) %></p>
    <p class="entry_detail" ><label class="entry_details">Date Rated:</label>  
      <%= @entry.updated_at %></p>
<% else %>
    <p class="entry_detail" ><label class="entry_details">Rating:</label>
      Not Rated Yet</p>  
<% end %>   
    <p class="entry_detail" ><label class="entry_details">Email:</label>  
      <%= @entry.contestant.email %>
    </p>
    <p class="entry_detail" ><label class="entry_details">First Name:</label>
      <%= @entry.first_name %>
    </p>
    <p class="entry_detail" ><label class="entry_details">Last Name:</label>
      <%=@entry.last_name%>
    </p>
    <p class="entry_detail" ><label class="entry_details">Address:</label>
      <%=@entry.address%>
    </p>
    <p class="entry_detail" ><label class="entry_details">Address2:</label>
      <%=@entry.address2%>
     </p>    
    <p class="entry_detail" ><label class="entry_details">City:</label>
      <%=@entry.city%></p>
    <p class="entry_detail" ><label class="entry_details">State:</label>
      <%=@entry.state%></p>    
    <p class="entry_detail" ><label class="entry_details">Zip:</label>
      <%=@entry.zip%></p>
    <p class="entry_detail" ><label class="entry_details">Phone:</label>
      <%=@entry.phone%></p>
    <p class="entry_detail" ><label class="entry_details">Photographer:</label>
      <%=@entry.photographer%></p>    
    <p class="entry_detail" ><label class="entry_details">Location:</label>
      <%=@entry.location%></p>
    <p class="entry_detail" ><label class="entry_details">Source:</label>
      <%=@entry.contest_source%></p>
    <p class="entry_detail" ><label class="entry_details">Entry Date:</label>
      <%=@entry.created_at%></p>
    <p class="entry_detail" ><label class="entry_details">Opted In?</label>
      <%=@entry.contestant.opt_in ?  "yes" : "no" %></p>
</div>
<br />
<%= link_to "Back to Gallery", contestant_entries_path %>

app/views/contestant_entries/stats.html.erb
<h1>Contest Statistics</h1>
<table width= "50%" >
  <tr  >
    <td class="entersubhead">Total Contest Submissions:</td>
    <td><strong><%= @stats["total_entries"] %></strong></td>
  </tr>
  <tr>
    <td class="entersubhead">Number of Rated Submissions:</td>
    <td><strong><%= @stats["total_rated"] %></strong></td>
  </tr>
  <tr>
    <td class="entersubhead">Unrated Submissions:</td>
    <td><strong><%= @stats["total_unrated"]%></strong></td>
  </tr>
</table>

app/views/contestant_entries/top_ten.html.erb
<h1>Top Ten For Each Month</h1>
<br />
<% @ratings_by_month.keys.each do |key| %> 
  <%# month was supplied then the key is in 1..12 %> 
  <% if key == 13 %>
    <h2>Month not specfied</h2>
  <% else %>
    <h2 class="entersubhead"><%= get_month_name(key) %></h2>
  <% end %>  
    <% @ratings_by_month[key].any? do  %>
    <ul class="top_ten_list">
      <% @ratings_by_month[key].each do |entry| %>        
      <li class="top_ten_item">
          <span>   
            <%= image_tag entry.photo.url(:thumb) %>
            <p>Rating: <%= entry.rating %></p>
            <p>Contestant: <%= entry.contestant.email %></p>
            <p>
              <%= link_to "Details", contestant_entry_path(entry),  :class=>"details_link" %>
            </p>
          </span>
      </li>
      <br />    
    <% end %>   <%# inner loop of rated entries %>
    </ul>
    <br />
  <% end %>     <%# test of whether month had ratings %>
<% end  %>      <%# outer loop of months %>