config/routes.rb
PhotoContest::Application.routes.draw do
    devise_for :users

    get "contestants/new"

    match 'contestant_entries/top_ten', :to =>  "contestant_entries#top_ten" , :as => :top_ten
    match 'contestant_entries/stats', :to =>  "contestant_entries#stats" , :as => :stats

    resources :contestants         
    resources :contestant_entries  
    
    #contest terminated
    match '/enter',   :to =>   'pages#enter'      
    #contest is running    
    #match '/enter',   :to =>   'contestants#new'  
  
    match '/rules',   :to =>   'pages#rules'
    match 'home',  :to =>  'pages#home'   
    root :to => 'pages#home' 

end

app/views/layouts/_admin_nav.html.erb
<div id="nav">
    <ul>
      <li><span class="navspace"><%= link_to "Home", home_path %></span></li>|
      <li><span class="navspace"><%= link_to "Gallery", contestant_entries_path %></span></li>|            
      <li><span class="navspace"><%= link_to "Stats", stats_path %></span></li>|
      <li><span class="navspace"><%= link_to "Top Ten", top_ten_path %></span></li>|
      <li><span class="navspace">              
        <% if user_signed_in? %>  
          <%= link_to('Logout', destroy_user_session_path, :method=> :delete) %> 
        <% else %>
          <%= link_to('Login', new_user_session_path)  %> 
        <% end %></span>             
      </li>
 </div>

app/views/layouts/_footer.html.erb
<div id="footer">  
  <div id="happylogo">
    <img
         src="<%= image_path(get_branded_asset("drivingcustlogo.png"))%>"               
         alt="Driving Customers Happy. It's our best policy."
         width="288" height="140" /></div>
  <div id="usagencieslink">
    <a href="<%= get_brand_url %>" target="_blank">
      <img src="<%= image_path(PhotoContest::Application.config.logo_asset_path)%>" width="324" height="68" border="0" class="bottomlogo" />
    </a>          
    <br />
    For a FREE QUOTE on low-cost auto insurance
    <a href="<%= get_brand_url %>" target="_blank">visit <%= get_brand %> today.</a></div>
    <span class="clear">&nbsp;</span>
</div><!-- footer -->

app/views/layouts/_head.html.erb
<head>
  <title>PICTURE THIS! calendar contest</title>
  <%= stylesheet_link_tag    "application" %>
  <link href='https://fonts.googleapis.com/css?family=Poly' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag "application" %>
  <style type="text/css" media="screen">#FlashID {visibility:inherit}</style>
  <%= csrf_meta_tags %>
</head>

app/views/layouts/_header.html.erb
<div id="header" >      
    <% path_to_flash = path_to_video(PhotoContest::Application.config.header_flash_asset_path) %>        
    <object id="FlashID" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" width="1024" height="400">          
      <param name="movie" value="<%= path_to_flash %>" />
      <param name="quality" value="high" />
      <param name="wmode" value="opaque" />
      <param name="swfversion" value="8.0.35.0" />
      <!-- This param tag prompts users with Flash Player 6.0 r65 and higher to download the latest version of Flash Player. Delete it if you don’t want users to see the prompt. -->
      <param name="expressinstall" value="Scripts/expressInstall.swf" />
      <!-- Next object tag is for non-IE browsers. So hide it from IE using IECC. -->
      <!--[if !IE]>-->
      <object type="application/x-shockwave-flash" data="<%= path_to_flash %>" width="1024" height="400">
        <!--<![endif]-->
        <param name="quality" value="high" />
        <param name="wmode" value="opaque" />
        <param name="swfversion" value="8.0.35.0" />
        <param name="expressinstall" value="Scripts/expressInstall.swf" />
        <!-- The browser displays the following alternative content for users with Flash Player 6.0 and older. -->
        <div>
          <h4>Content on this page requires a newer version of Adobe Flash Player.</h4>
          <p><a href="https://www.adobe.com/go/getflashplayer">
            <img src="https://www.adobe.com/images/shared/download_buttons/get_flash_player.gif"
                 alt="Get Adobe Flash player" width="112" height="33" /></a>
          </p>
        </div>
        <!--[if !IE]>-->
      </object>
      <!--<![endif]-->
    </object>
</div><!-- header-->      

app/views/layouts/_nav.html.erb
<div id="nav">
  <ul>            
    <li><span class="navspace"><%= link_to "Home", home_path %></span></li>|    
    <li><span class="navspace"><%= link_to "Enter", enter_path %></span></li>|
    <li><span class="navspace"><%= link_to "Rules", rules_path %></span></li>    
  </ul>          
</nav>
</div>

app/views/layouts/_sidebar.html.erb
<div id="sidebar">
  <%= image_tag("calendars.png", :alt=>"Calendars", :width=>"345", :height => "687") %>           
  <br />
  <%= image_tag(get_branded_asset("mycommlogo.png"),
                :alt=>"My Community",
                :width=>"303",
                :height => "175", 
                :class => "mycommpadding") %>           
</div><!-- sidebar -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render 'layouts/head' %>
  <body>
    <div id="wrap">
      <%= render 'layouts/header' %>
      <%= render 'layouts/nav' %>       
      <div id="main">        
        <section>
          <% flash.each do |key, value| %>
            <%= content_tag(:div, value, :class => "flash #{key}") unless value == "Success" %>
          <% end %>
          
          <%= yield %>
        </section>        
      </div><!-- main --->
      <%= render 'layouts/sidebar' %>
      <%= render 'layouts/footer' %>               
    </div><!-- wrap -->  
    <%= debug(params) if Rails.env.development? %>
    </body>
</html>

app/views/layouts/contestant_entries.html.erb
<!DOCTYPE html>
<html>
  <%= render 'layouts/head' %>
  <body>
    <div id="wrap">
       <%= render 'layouts/header' %>
       <%= render 'layouts/admin_nav' %>
      <div id="main_gallery"> 
        <section>
          <% flash.each do |key, value| %>
            <%= content_tag(:div, value, :class => "flash #{key}")  unless value ="Success" %>
          <% end %>
          <%= yield %>        
        </section>
      </div>
      <div id="sidebar_gallery">
      </div><!-- sidebar -->
     <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
   </body>
</html>